---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: HTTPRoute
      name: kubernetes-dashboard-auth
    patch: |-
      - op: add
        path: /spec/hostnames/-
        value: "www.dudo.dev"
  - target:
      kind: HTTPRoute
      name: kubernetes-dashboard-api
    patch: |-
      - op: add
        path: /spec/hostnames/-
        value: "www.dudo.dev"
  - target:
      kind: HTTPRoute
      name: kubernetes-dashboard-web
    patch: |-
      - op: add
        path: /spec/hostnames/-
        value: "www.dudo.dev"
